packages:
  - '.'

allowBuilds:
  core-js: true
  electron: true
  esbuild: true
  electron-winstaller: true
  grandiose: set this to true or false

overrides:
  shell-quote: ">=1.8.4"
  tar: ">=7.5.7"
  esbuild: ">=0.28.1"
  cookie: ">=0.7.0"
