//! Remote-WS panel: IP:port + token (for the phone to type into a URL) and
//! a Start/Stop button (Task 14 of the plan).
//!
//! Takes individual fields, not `&mut AppState`, same convention as the
//! other panels (`ui::midi`, `ui::ndi`, `ui::osc`). Unlike `ui::osc`, there
//! is no user-editable field to read at click time: the port is always
//! OS-assigned and the token always freshly generated by the thread itself
//! (`RemoteWsControl::Start` takes no arguments), so this panel only ever
//! displays `RemoteWsSnapshot`, it never owns any of its own state.
//!
//! No QR code: a bonus, not requested, deliberately not added (brief is
//! explicit). No soft-takeover, no mapping/learn UI, same reasoning as
//! `ui::osc`.

use opendrop_io::remote_ws::{RemoteWsControl, RemoteWsHandle};

pub fn show(ui: &mut egui::Ui, remote_ws: &RemoteWsHandle) {
    let snapshot = remote_ws.latest();

    if snapshot.listening {
        let host = snapshot.ip.as_deref().unwrap_or("(no LAN IP detected)");
        ui.label(format!("Remote: listening on {host}:{}", snapshot.port));
        ui.horizontal(|ui| {
            ui.label("Token");
            ui.monospace(&snapshot.token);
        });
        if snapshot.ip.is_some() {
            ui.label(format!(
                "URL: http://{host}:{}/remote?host={host}&port={}&token={}",
                snapshot.port, snapshot.port, snapshot.token
            ));
        }
        if ui.button("Stop").clicked() {
            let _ = remote_ws.control_tx.send(RemoteWsControl::Stop);
        }
    } else {
        ui.label("Remote: not listening");
        if ui.button("Start").clicked() {
            let _ = remote_ws.control_tx.send(RemoteWsControl::Start);
        }
    }
}
