[package]
name = "opendrop-app"
version = "0.1.0"
edition = "2021"

[dependencies]
opendrop-core = { path = "../core" }
opendrop-engine = { path = "../engine" }
opendrop-audio = { path = "../audio" }
winit = "0.30.13"
glutin = "0.32.3"
glutin-winit = "0.5.0"
glow = "0.17"
raw-window-handle = "0.6"
egui = "0.36.1"
egui_glow = { version = "0.36.1", features = ["winit"] }
khronos-egl = { version = "6", features = ["dynamic"] }
