//! Kebab-case wire-format translation table for `opendrop_core::commands::CommandId`.
//!
//! The wire format (OSC addresses, remote-WS payloads) uses the exact kebab-case
//! strings from OpenDrop-VJ `src/lib/engine/commands.ts` (`export type CommandId = ...`),
//! not a mechanically-derived kebab-case of the Rust variant name. Each pair below was
//! checked against `commands.ts` position-by-position (both lists share the same order
//! and section grouping); no naming divergence was found: every TS string literal is
//! in fact the mechanical kebab-case conversion of the corresponding Rust variant name.
//!
//! Pure, no I/O: consumed by OSC (Step 11) and remote WS (Step 12).

use opendrop_core::commands::CommandId;

/// Parse a wire-format kebab-case command id into a `CommandId`. Returns `None` for
/// any string that doesn't exactly match one of the 223 known ids.
pub fn parse_command_id(s: &str) -> Option<CommandId> {
    Some(match s {
        "crossfader" => CommandId::Crossfader,
        "preset-prev-a" => CommandId::PresetPrevA,
        "preset-next-a" => CommandId::PresetNextA,
        "preset-prev-b" => CommandId::PresetPrevB,
        "preset-next-b" => CommandId::PresetNextB,
        "playlist-toggle-a" => CommandId::PlaylistToggleA,
        "playlist-toggle-b" => CommandId::PlaylistToggleB,
        "playlist-prev-a" => CommandId::PlaylistPrevA,
        "playlist-next-a" => CommandId::PlaylistNextA,
        "playlist-prev-b" => CommandId::PlaylistPrevB,
        "playlist-next-b" => CommandId::PlaylistNextB,
        "crossfader-left" => CommandId::CrossfaderLeft,
        "crossfader-right" => CommandId::CrossfaderRight,
        "deck-switch" => CommandId::DeckSwitch,
        "preset-prev-active" => CommandId::PresetPrevActive,
        "preset-next-active" => CommandId::PresetNextActive,
        "playlist-toggle-active" => CommandId::PlaylistToggleActive,
        "playlist-prev-active" => CommandId::PlaylistPrevActive,
        "playlist-next-active" => CommandId::PlaylistNextActive,
        "strobe-toggle" => CommandId::StrobeToggle,
        "lfo-rate-up" => CommandId::LfoRateUp,
        "lfo-rate-down" => CommandId::LfoRateDown,
        "color-hue-a" => CommandId::ColorHueA,
        "color-sat-a" => CommandId::ColorSatA,
        "color-bright-a" => CommandId::ColorBrightA,
        "color-contrast-a" => CommandId::ColorContrastA,
        "color-invert-a" => CommandId::ColorInvertA,
        "color-hue-b" => CommandId::ColorHueB,
        "color-sat-b" => CommandId::ColorSatB,
        "color-bright-b" => CommandId::ColorBrightB,
        "color-contrast-b" => CommandId::ColorContrastB,
        "color-invert-b" => CommandId::ColorInvertB,
        "composite-blend-0" => CommandId::CompositeBlend0,
        "composite-blend-1" => CommandId::CompositeBlend1,
        "composite-blend-2" => CommandId::CompositeBlend2,
        "composite-blend-3" => CommandId::CompositeBlend3,
        "lumakey-black-0" => CommandId::LumakeyBlack0,
        "lumakey-black-1" => CommandId::LumakeyBlack1,
        "lumakey-black-2" => CommandId::LumakeyBlack2,
        "lumakey-black-3" => CommandId::LumakeyBlack3,
        "lumakey-white-0" => CommandId::LumakeyWhite0,
        "lumakey-white-1" => CommandId::LumakeyWhite1,
        "lumakey-white-2" => CommandId::LumakeyWhite2,
        "lumakey-white-3" => CommandId::LumakeyWhite3,
        "colorkey-hue-0" => CommandId::ColorkeyHue0,
        "colorkey-hue-1" => CommandId::ColorkeyHue1,
        "colorkey-hue-2" => CommandId::ColorkeyHue2,
        "colorkey-hue-3" => CommandId::ColorkeyHue3,
        "colorkey-tolerance-0" => CommandId::ColorkeyTolerance0,
        "colorkey-tolerance-1" => CommandId::ColorkeyTolerance1,
        "colorkey-tolerance-2" => CommandId::ColorkeyTolerance2,
        "colorkey-tolerance-3" => CommandId::ColorkeyTolerance3,
        "recall-snapshot-0" => CommandId::RecallSnapshot0,
        "recall-snapshot-1" => CommandId::RecallSnapshot1,
        "recall-snapshot-2" => CommandId::RecallSnapshot2,
        "recall-snapshot-3" => CommandId::RecallSnapshot3,
        "recall-snapshot-4" => CommandId::RecallSnapshot4,
        "recall-snapshot-5" => CommandId::RecallSnapshot5,
        "recall-snapshot-6" => CommandId::RecallSnapshot6,
        "recall-snapshot-7" => CommandId::RecallSnapshot7,
        "time-speed-0" => CommandId::TimeSpeed0,
        "time-speed-1" => CommandId::TimeSpeed1,
        "time-speed-2" => CommandId::TimeSpeed2,
        "time-speed-3" => CommandId::TimeSpeed3,
        "time-zoom-0" => CommandId::TimeZoom0,
        "time-zoom-1" => CommandId::TimeZoom1,
        "time-zoom-2" => CommandId::TimeZoom2,
        "time-zoom-3" => CommandId::TimeZoom3,
        "time-rot-0" => CommandId::TimeRot0,
        "time-rot-1" => CommandId::TimeRot1,
        "time-rot-2" => CommandId::TimeRot2,
        "time-rot-3" => CommandId::TimeRot3,
        "time-warp-0" => CommandId::TimeWarp0,
        "time-warp-1" => CommandId::TimeWarp1,
        "time-warp-2" => CommandId::TimeWarp2,
        "time-warp-3" => CommandId::TimeWarp3,
        "time-dx-0" => CommandId::TimeDx0,
        "time-dx-1" => CommandId::TimeDx1,
        "time-dx-2" => CommandId::TimeDx2,
        "time-dx-3" => CommandId::TimeDx3,
        "time-dy-0" => CommandId::TimeDy0,
        "time-dy-1" => CommandId::TimeDy1,
        "time-dy-2" => CommandId::TimeDy2,
        "time-dy-3" => CommandId::TimeDy3,
        "time-stretch-0" => CommandId::TimeStretch0,
        "time-stretch-1" => CommandId::TimeStretch1,
        "time-stretch-2" => CommandId::TimeStretch2,
        "time-stretch-3" => CommandId::TimeStretch3,
        "time-wave-0" => CommandId::TimeWave0,
        "time-wave-1" => CommandId::TimeWave1,
        "time-wave-2" => CommandId::TimeWave2,
        "time-wave-3" => CommandId::TimeWave3,
        "overlay-queue-next" => CommandId::OverlayQueueNext,
        "overlay-queue-prev" => CommandId::OverlayQueuePrev,
        "timeline-toggle" => CommandId::TimelineToggle,
        "qvar-1-0" => CommandId::Qvar1_0,
        "qvar-1-1" => CommandId::Qvar1_1,
        "qvar-1-2" => CommandId::Qvar1_2,
        "qvar-1-3" => CommandId::Qvar1_3,
        "qvar-2-0" => CommandId::Qvar2_0,
        "qvar-2-1" => CommandId::Qvar2_1,
        "qvar-2-2" => CommandId::Qvar2_2,
        "qvar-2-3" => CommandId::Qvar2_3,
        "qvar-3-0" => CommandId::Qvar3_0,
        "qvar-3-1" => CommandId::Qvar3_1,
        "qvar-3-2" => CommandId::Qvar3_2,
        "qvar-3-3" => CommandId::Qvar3_3,
        "qvar-4-0" => CommandId::Qvar4_0,
        "qvar-4-1" => CommandId::Qvar4_1,
        "qvar-4-2" => CommandId::Qvar4_2,
        "qvar-4-3" => CommandId::Qvar4_3,
        "qvar-5-0" => CommandId::Qvar5_0,
        "qvar-5-1" => CommandId::Qvar5_1,
        "qvar-5-2" => CommandId::Qvar5_2,
        "qvar-5-3" => CommandId::Qvar5_3,
        "qvar-6-0" => CommandId::Qvar6_0,
        "qvar-6-1" => CommandId::Qvar6_1,
        "qvar-6-2" => CommandId::Qvar6_2,
        "qvar-6-3" => CommandId::Qvar6_3,
        "qvar-7-0" => CommandId::Qvar7_0,
        "qvar-7-1" => CommandId::Qvar7_1,
        "qvar-7-2" => CommandId::Qvar7_2,
        "qvar-7-3" => CommandId::Qvar7_3,
        "qvar-8-0" => CommandId::Qvar8_0,
        "qvar-8-1" => CommandId::Qvar8_1,
        "qvar-8-2" => CommandId::Qvar8_2,
        "qvar-8-3" => CommandId::Qvar8_3,
        "qvar-9-0" => CommandId::Qvar9_0,
        "qvar-9-1" => CommandId::Qvar9_1,
        "qvar-9-2" => CommandId::Qvar9_2,
        "qvar-9-3" => CommandId::Qvar9_3,
        "qvar-10-0" => CommandId::Qvar10_0,
        "qvar-10-1" => CommandId::Qvar10_1,
        "qvar-10-2" => CommandId::Qvar10_2,
        "qvar-10-3" => CommandId::Qvar10_3,
        "qvar-11-0" => CommandId::Qvar11_0,
        "qvar-11-1" => CommandId::Qvar11_1,
        "qvar-11-2" => CommandId::Qvar11_2,
        "qvar-11-3" => CommandId::Qvar11_3,
        "qvar-12-0" => CommandId::Qvar12_0,
        "qvar-12-1" => CommandId::Qvar12_1,
        "qvar-12-2" => CommandId::Qvar12_2,
        "qvar-12-3" => CommandId::Qvar12_3,
        "qvar-13-0" => CommandId::Qvar13_0,
        "qvar-13-1" => CommandId::Qvar13_1,
        "qvar-13-2" => CommandId::Qvar13_2,
        "qvar-13-3" => CommandId::Qvar13_3,
        "qvar-14-0" => CommandId::Qvar14_0,
        "qvar-14-1" => CommandId::Qvar14_1,
        "qvar-14-2" => CommandId::Qvar14_2,
        "qvar-14-3" => CommandId::Qvar14_3,
        "qvar-15-0" => CommandId::Qvar15_0,
        "qvar-15-1" => CommandId::Qvar15_1,
        "qvar-15-2" => CommandId::Qvar15_2,
        "qvar-15-3" => CommandId::Qvar15_3,
        "qvar-16-0" => CommandId::Qvar16_0,
        "qvar-16-1" => CommandId::Qvar16_1,
        "qvar-16-2" => CommandId::Qvar16_2,
        "qvar-16-3" => CommandId::Qvar16_3,
        "qvar-17-0" => CommandId::Qvar17_0,
        "qvar-17-1" => CommandId::Qvar17_1,
        "qvar-17-2" => CommandId::Qvar17_2,
        "qvar-17-3" => CommandId::Qvar17_3,
        "qvar-18-0" => CommandId::Qvar18_0,
        "qvar-18-1" => CommandId::Qvar18_1,
        "qvar-18-2" => CommandId::Qvar18_2,
        "qvar-18-3" => CommandId::Qvar18_3,
        "qvar-19-0" => CommandId::Qvar19_0,
        "qvar-19-1" => CommandId::Qvar19_1,
        "qvar-19-2" => CommandId::Qvar19_2,
        "qvar-19-3" => CommandId::Qvar19_3,
        "qvar-20-0" => CommandId::Qvar20_0,
        "qvar-20-1" => CommandId::Qvar20_1,
        "qvar-20-2" => CommandId::Qvar20_2,
        "qvar-20-3" => CommandId::Qvar20_3,
        "qvar-21-0" => CommandId::Qvar21_0,
        "qvar-21-1" => CommandId::Qvar21_1,
        "qvar-21-2" => CommandId::Qvar21_2,
        "qvar-21-3" => CommandId::Qvar21_3,
        "qvar-22-0" => CommandId::Qvar22_0,
        "qvar-22-1" => CommandId::Qvar22_1,
        "qvar-22-2" => CommandId::Qvar22_2,
        "qvar-22-3" => CommandId::Qvar22_3,
        "qvar-23-0" => CommandId::Qvar23_0,
        "qvar-23-1" => CommandId::Qvar23_1,
        "qvar-23-2" => CommandId::Qvar23_2,
        "qvar-23-3" => CommandId::Qvar23_3,
        "qvar-24-0" => CommandId::Qvar24_0,
        "qvar-24-1" => CommandId::Qvar24_1,
        "qvar-24-2" => CommandId::Qvar24_2,
        "qvar-24-3" => CommandId::Qvar24_3,
        "qvar-25-0" => CommandId::Qvar25_0,
        "qvar-25-1" => CommandId::Qvar25_1,
        "qvar-25-2" => CommandId::Qvar25_2,
        "qvar-25-3" => CommandId::Qvar25_3,
        "qvar-26-0" => CommandId::Qvar26_0,
        "qvar-26-1" => CommandId::Qvar26_1,
        "qvar-26-2" => CommandId::Qvar26_2,
        "qvar-26-3" => CommandId::Qvar26_3,
        "qvar-27-0" => CommandId::Qvar27_0,
        "qvar-27-1" => CommandId::Qvar27_1,
        "qvar-27-2" => CommandId::Qvar27_2,
        "qvar-27-3" => CommandId::Qvar27_3,
        "qvar-28-0" => CommandId::Qvar28_0,
        "qvar-28-1" => CommandId::Qvar28_1,
        "qvar-28-2" => CommandId::Qvar28_2,
        "qvar-28-3" => CommandId::Qvar28_3,
        "qvar-29-0" => CommandId::Qvar29_0,
        "qvar-29-1" => CommandId::Qvar29_1,
        "qvar-29-2" => CommandId::Qvar29_2,
        "qvar-29-3" => CommandId::Qvar29_3,
        "qvar-30-0" => CommandId::Qvar30_0,
        "qvar-30-1" => CommandId::Qvar30_1,
        "qvar-30-2" => CommandId::Qvar30_2,
        "qvar-30-3" => CommandId::Qvar30_3,
        "qvar-31-0" => CommandId::Qvar31_0,
        "qvar-31-1" => CommandId::Qvar31_1,
        "qvar-31-2" => CommandId::Qvar31_2,
        "qvar-31-3" => CommandId::Qvar31_3,
        "qvar-32-0" => CommandId::Qvar32_0,
        "qvar-32-1" => CommandId::Qvar32_1,
        "qvar-32-2" => CommandId::Qvar32_2,
        "qvar-32-3" => CommandId::Qvar32_3,
        _ => return None,
    })
}

/// The inverse of [`parse_command_id`]: the wire-format kebab-case string for a `CommandId`.
pub fn command_id_name(id: CommandId) -> &'static str {
    match id {
        CommandId::Crossfader => "crossfader",
        CommandId::PresetPrevA => "preset-prev-a",
        CommandId::PresetNextA => "preset-next-a",
        CommandId::PresetPrevB => "preset-prev-b",
        CommandId::PresetNextB => "preset-next-b",
        CommandId::PlaylistToggleA => "playlist-toggle-a",
        CommandId::PlaylistToggleB => "playlist-toggle-b",
        CommandId::PlaylistPrevA => "playlist-prev-a",
        CommandId::PlaylistNextA => "playlist-next-a",
        CommandId::PlaylistPrevB => "playlist-prev-b",
        CommandId::PlaylistNextB => "playlist-next-b",
        CommandId::CrossfaderLeft => "crossfader-left",
        CommandId::CrossfaderRight => "crossfader-right",
        CommandId::DeckSwitch => "deck-switch",
        CommandId::PresetPrevActive => "preset-prev-active",
        CommandId::PresetNextActive => "preset-next-active",
        CommandId::PlaylistToggleActive => "playlist-toggle-active",
        CommandId::PlaylistPrevActive => "playlist-prev-active",
        CommandId::PlaylistNextActive => "playlist-next-active",
        CommandId::StrobeToggle => "strobe-toggle",
        CommandId::LfoRateUp => "lfo-rate-up",
        CommandId::LfoRateDown => "lfo-rate-down",
        CommandId::ColorHueA => "color-hue-a",
        CommandId::ColorSatA => "color-sat-a",
        CommandId::ColorBrightA => "color-bright-a",
        CommandId::ColorContrastA => "color-contrast-a",
        CommandId::ColorInvertA => "color-invert-a",
        CommandId::ColorHueB => "color-hue-b",
        CommandId::ColorSatB => "color-sat-b",
        CommandId::ColorBrightB => "color-bright-b",
        CommandId::ColorContrastB => "color-contrast-b",
        CommandId::ColorInvertB => "color-invert-b",
        CommandId::CompositeBlend0 => "composite-blend-0",
        CommandId::CompositeBlend1 => "composite-blend-1",
        CommandId::CompositeBlend2 => "composite-blend-2",
        CommandId::CompositeBlend3 => "composite-blend-3",
        CommandId::LumakeyBlack0 => "lumakey-black-0",
        CommandId::LumakeyBlack1 => "lumakey-black-1",
        CommandId::LumakeyBlack2 => "lumakey-black-2",
        CommandId::LumakeyBlack3 => "lumakey-black-3",
        CommandId::LumakeyWhite0 => "lumakey-white-0",
        CommandId::LumakeyWhite1 => "lumakey-white-1",
        CommandId::LumakeyWhite2 => "lumakey-white-2",
        CommandId::LumakeyWhite3 => "lumakey-white-3",
        CommandId::ColorkeyHue0 => "colorkey-hue-0",
        CommandId::ColorkeyHue1 => "colorkey-hue-1",
        CommandId::ColorkeyHue2 => "colorkey-hue-2",
        CommandId::ColorkeyHue3 => "colorkey-hue-3",
        CommandId::ColorkeyTolerance0 => "colorkey-tolerance-0",
        CommandId::ColorkeyTolerance1 => "colorkey-tolerance-1",
        CommandId::ColorkeyTolerance2 => "colorkey-tolerance-2",
        CommandId::ColorkeyTolerance3 => "colorkey-tolerance-3",
        CommandId::RecallSnapshot0 => "recall-snapshot-0",
        CommandId::RecallSnapshot1 => "recall-snapshot-1",
        CommandId::RecallSnapshot2 => "recall-snapshot-2",
        CommandId::RecallSnapshot3 => "recall-snapshot-3",
        CommandId::RecallSnapshot4 => "recall-snapshot-4",
        CommandId::RecallSnapshot5 => "recall-snapshot-5",
        CommandId::RecallSnapshot6 => "recall-snapshot-6",
        CommandId::RecallSnapshot7 => "recall-snapshot-7",
        CommandId::TimeSpeed0 => "time-speed-0",
        CommandId::TimeSpeed1 => "time-speed-1",
        CommandId::TimeSpeed2 => "time-speed-2",
        CommandId::TimeSpeed3 => "time-speed-3",
        CommandId::TimeZoom0 => "time-zoom-0",
        CommandId::TimeZoom1 => "time-zoom-1",
        CommandId::TimeZoom2 => "time-zoom-2",
        CommandId::TimeZoom3 => "time-zoom-3",
        CommandId::TimeRot0 => "time-rot-0",
        CommandId::TimeRot1 => "time-rot-1",
        CommandId::TimeRot2 => "time-rot-2",
        CommandId::TimeRot3 => "time-rot-3",
        CommandId::TimeWarp0 => "time-warp-0",
        CommandId::TimeWarp1 => "time-warp-1",
        CommandId::TimeWarp2 => "time-warp-2",
        CommandId::TimeWarp3 => "time-warp-3",
        CommandId::TimeDx0 => "time-dx-0",
        CommandId::TimeDx1 => "time-dx-1",
        CommandId::TimeDx2 => "time-dx-2",
        CommandId::TimeDx3 => "time-dx-3",
        CommandId::TimeDy0 => "time-dy-0",
        CommandId::TimeDy1 => "time-dy-1",
        CommandId::TimeDy2 => "time-dy-2",
        CommandId::TimeDy3 => "time-dy-3",
        CommandId::TimeStretch0 => "time-stretch-0",
        CommandId::TimeStretch1 => "time-stretch-1",
        CommandId::TimeStretch2 => "time-stretch-2",
        CommandId::TimeStretch3 => "time-stretch-3",
        CommandId::TimeWave0 => "time-wave-0",
        CommandId::TimeWave1 => "time-wave-1",
        CommandId::TimeWave2 => "time-wave-2",
        CommandId::TimeWave3 => "time-wave-3",
        CommandId::OverlayQueueNext => "overlay-queue-next",
        CommandId::OverlayQueuePrev => "overlay-queue-prev",
        CommandId::TimelineToggle => "timeline-toggle",
        CommandId::Qvar1_0 => "qvar-1-0",
        CommandId::Qvar1_1 => "qvar-1-1",
        CommandId::Qvar1_2 => "qvar-1-2",
        CommandId::Qvar1_3 => "qvar-1-3",
        CommandId::Qvar2_0 => "qvar-2-0",
        CommandId::Qvar2_1 => "qvar-2-1",
        CommandId::Qvar2_2 => "qvar-2-2",
        CommandId::Qvar2_3 => "qvar-2-3",
        CommandId::Qvar3_0 => "qvar-3-0",
        CommandId::Qvar3_1 => "qvar-3-1",
        CommandId::Qvar3_2 => "qvar-3-2",
        CommandId::Qvar3_3 => "qvar-3-3",
        CommandId::Qvar4_0 => "qvar-4-0",
        CommandId::Qvar4_1 => "qvar-4-1",
        CommandId::Qvar4_2 => "qvar-4-2",
        CommandId::Qvar4_3 => "qvar-4-3",
        CommandId::Qvar5_0 => "qvar-5-0",
        CommandId::Qvar5_1 => "qvar-5-1",
        CommandId::Qvar5_2 => "qvar-5-2",
        CommandId::Qvar5_3 => "qvar-5-3",
        CommandId::Qvar6_0 => "qvar-6-0",
        CommandId::Qvar6_1 => "qvar-6-1",
        CommandId::Qvar6_2 => "qvar-6-2",
        CommandId::Qvar6_3 => "qvar-6-3",
        CommandId::Qvar7_0 => "qvar-7-0",
        CommandId::Qvar7_1 => "qvar-7-1",
        CommandId::Qvar7_2 => "qvar-7-2",
        CommandId::Qvar7_3 => "qvar-7-3",
        CommandId::Qvar8_0 => "qvar-8-0",
        CommandId::Qvar8_1 => "qvar-8-1",
        CommandId::Qvar8_2 => "qvar-8-2",
        CommandId::Qvar8_3 => "qvar-8-3",
        CommandId::Qvar9_0 => "qvar-9-0",
        CommandId::Qvar9_1 => "qvar-9-1",
        CommandId::Qvar9_2 => "qvar-9-2",
        CommandId::Qvar9_3 => "qvar-9-3",
        CommandId::Qvar10_0 => "qvar-10-0",
        CommandId::Qvar10_1 => "qvar-10-1",
        CommandId::Qvar10_2 => "qvar-10-2",
        CommandId::Qvar10_3 => "qvar-10-3",
        CommandId::Qvar11_0 => "qvar-11-0",
        CommandId::Qvar11_1 => "qvar-11-1",
        CommandId::Qvar11_2 => "qvar-11-2",
        CommandId::Qvar11_3 => "qvar-11-3",
        CommandId::Qvar12_0 => "qvar-12-0",
        CommandId::Qvar12_1 => "qvar-12-1",
        CommandId::Qvar12_2 => "qvar-12-2",
        CommandId::Qvar12_3 => "qvar-12-3",
        CommandId::Qvar13_0 => "qvar-13-0",
        CommandId::Qvar13_1 => "qvar-13-1",
        CommandId::Qvar13_2 => "qvar-13-2",
        CommandId::Qvar13_3 => "qvar-13-3",
        CommandId::Qvar14_0 => "qvar-14-0",
        CommandId::Qvar14_1 => "qvar-14-1",
        CommandId::Qvar14_2 => "qvar-14-2",
        CommandId::Qvar14_3 => "qvar-14-3",
        CommandId::Qvar15_0 => "qvar-15-0",
        CommandId::Qvar15_1 => "qvar-15-1",
        CommandId::Qvar15_2 => "qvar-15-2",
        CommandId::Qvar15_3 => "qvar-15-3",
        CommandId::Qvar16_0 => "qvar-16-0",
        CommandId::Qvar16_1 => "qvar-16-1",
        CommandId::Qvar16_2 => "qvar-16-2",
        CommandId::Qvar16_3 => "qvar-16-3",
        CommandId::Qvar17_0 => "qvar-17-0",
        CommandId::Qvar17_1 => "qvar-17-1",
        CommandId::Qvar17_2 => "qvar-17-2",
        CommandId::Qvar17_3 => "qvar-17-3",
        CommandId::Qvar18_0 => "qvar-18-0",
        CommandId::Qvar18_1 => "qvar-18-1",
        CommandId::Qvar18_2 => "qvar-18-2",
        CommandId::Qvar18_3 => "qvar-18-3",
        CommandId::Qvar19_0 => "qvar-19-0",
        CommandId::Qvar19_1 => "qvar-19-1",
        CommandId::Qvar19_2 => "qvar-19-2",
        CommandId::Qvar19_3 => "qvar-19-3",
        CommandId::Qvar20_0 => "qvar-20-0",
        CommandId::Qvar20_1 => "qvar-20-1",
        CommandId::Qvar20_2 => "qvar-20-2",
        CommandId::Qvar20_3 => "qvar-20-3",
        CommandId::Qvar21_0 => "qvar-21-0",
        CommandId::Qvar21_1 => "qvar-21-1",
        CommandId::Qvar21_2 => "qvar-21-2",
        CommandId::Qvar21_3 => "qvar-21-3",
        CommandId::Qvar22_0 => "qvar-22-0",
        CommandId::Qvar22_1 => "qvar-22-1",
        CommandId::Qvar22_2 => "qvar-22-2",
        CommandId::Qvar22_3 => "qvar-22-3",
        CommandId::Qvar23_0 => "qvar-23-0",
        CommandId::Qvar23_1 => "qvar-23-1",
        CommandId::Qvar23_2 => "qvar-23-2",
        CommandId::Qvar23_3 => "qvar-23-3",
        CommandId::Qvar24_0 => "qvar-24-0",
        CommandId::Qvar24_1 => "qvar-24-1",
        CommandId::Qvar24_2 => "qvar-24-2",
        CommandId::Qvar24_3 => "qvar-24-3",
        CommandId::Qvar25_0 => "qvar-25-0",
        CommandId::Qvar25_1 => "qvar-25-1",
        CommandId::Qvar25_2 => "qvar-25-2",
        CommandId::Qvar25_3 => "qvar-25-3",
        CommandId::Qvar26_0 => "qvar-26-0",
        CommandId::Qvar26_1 => "qvar-26-1",
        CommandId::Qvar26_2 => "qvar-26-2",
        CommandId::Qvar26_3 => "qvar-26-3",
        CommandId::Qvar27_0 => "qvar-27-0",
        CommandId::Qvar27_1 => "qvar-27-1",
        CommandId::Qvar27_2 => "qvar-27-2",
        CommandId::Qvar27_3 => "qvar-27-3",
        CommandId::Qvar28_0 => "qvar-28-0",
        CommandId::Qvar28_1 => "qvar-28-1",
        CommandId::Qvar28_2 => "qvar-28-2",
        CommandId::Qvar28_3 => "qvar-28-3",
        CommandId::Qvar29_0 => "qvar-29-0",
        CommandId::Qvar29_1 => "qvar-29-1",
        CommandId::Qvar29_2 => "qvar-29-2",
        CommandId::Qvar29_3 => "qvar-29-3",
        CommandId::Qvar30_0 => "qvar-30-0",
        CommandId::Qvar30_1 => "qvar-30-1",
        CommandId::Qvar30_2 => "qvar-30-2",
        CommandId::Qvar30_3 => "qvar-30-3",
        CommandId::Qvar31_0 => "qvar-31-0",
        CommandId::Qvar31_1 => "qvar-31-1",
        CommandId::Qvar31_2 => "qvar-31-2",
        CommandId::Qvar31_3 => "qvar-31-3",
        CommandId::Qvar32_0 => "qvar-32-0",
        CommandId::Qvar32_1 => "qvar-32-1",
        CommandId::Qvar32_2 => "qvar-32-2",
        CommandId::Qvar32_3 => "qvar-32-3",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// All 223 `CommandId` variants, listed by hand (no `strum` dependency in this
    /// workspace, see `core/Cargo.toml`). Order mirrors the enum declaration in
    /// `core/src/commands.rs`.
    const ALL: &[CommandId] = &[
        CommandId::Crossfader,
        CommandId::PresetPrevA,
        CommandId::PresetNextA,
        CommandId::PresetPrevB,
        CommandId::PresetNextB,
        CommandId::PlaylistToggleA,
        CommandId::PlaylistToggleB,
        CommandId::PlaylistPrevA,
        CommandId::PlaylistNextA,
        CommandId::PlaylistPrevB,
        CommandId::PlaylistNextB,
        CommandId::CrossfaderLeft,
        CommandId::CrossfaderRight,
        CommandId::DeckSwitch,
        CommandId::PresetPrevActive,
        CommandId::PresetNextActive,
        CommandId::PlaylistToggleActive,
        CommandId::PlaylistPrevActive,
        CommandId::PlaylistNextActive,
        CommandId::StrobeToggle,
        CommandId::LfoRateUp,
        CommandId::LfoRateDown,
        CommandId::ColorHueA,
        CommandId::ColorSatA,
        CommandId::ColorBrightA,
        CommandId::ColorContrastA,
        CommandId::ColorInvertA,
        CommandId::ColorHueB,
        CommandId::ColorSatB,
        CommandId::ColorBrightB,
        CommandId::ColorContrastB,
        CommandId::ColorInvertB,
        CommandId::CompositeBlend0,
        CommandId::CompositeBlend1,
        CommandId::CompositeBlend2,
        CommandId::CompositeBlend3,
        CommandId::LumakeyBlack0,
        CommandId::LumakeyBlack1,
        CommandId::LumakeyBlack2,
        CommandId::LumakeyBlack3,
        CommandId::LumakeyWhite0,
        CommandId::LumakeyWhite1,
        CommandId::LumakeyWhite2,
        CommandId::LumakeyWhite3,
        CommandId::ColorkeyHue0,
        CommandId::ColorkeyHue1,
        CommandId::ColorkeyHue2,
        CommandId::ColorkeyHue3,
        CommandId::ColorkeyTolerance0,
        CommandId::ColorkeyTolerance1,
        CommandId::ColorkeyTolerance2,
        CommandId::ColorkeyTolerance3,
        CommandId::RecallSnapshot0,
        CommandId::RecallSnapshot1,
        CommandId::RecallSnapshot2,
        CommandId::RecallSnapshot3,
        CommandId::RecallSnapshot4,
        CommandId::RecallSnapshot5,
        CommandId::RecallSnapshot6,
        CommandId::RecallSnapshot7,
        CommandId::TimeSpeed0,
        CommandId::TimeSpeed1,
        CommandId::TimeSpeed2,
        CommandId::TimeSpeed3,
        CommandId::TimeZoom0,
        CommandId::TimeZoom1,
        CommandId::TimeZoom2,
        CommandId::TimeZoom3,
        CommandId::TimeRot0,
        CommandId::TimeRot1,
        CommandId::TimeRot2,
        CommandId::TimeRot3,
        CommandId::TimeWarp0,
        CommandId::TimeWarp1,
        CommandId::TimeWarp2,
        CommandId::TimeWarp3,
        CommandId::TimeDx0,
        CommandId::TimeDx1,
        CommandId::TimeDx2,
        CommandId::TimeDx3,
        CommandId::TimeDy0,
        CommandId::TimeDy1,
        CommandId::TimeDy2,
        CommandId::TimeDy3,
        CommandId::TimeStretch0,
        CommandId::TimeStretch1,
        CommandId::TimeStretch2,
        CommandId::TimeStretch3,
        CommandId::TimeWave0,
        CommandId::TimeWave1,
        CommandId::TimeWave2,
        CommandId::TimeWave3,
        CommandId::OverlayQueueNext,
        CommandId::OverlayQueuePrev,
        CommandId::TimelineToggle,
        CommandId::Qvar1_0,
        CommandId::Qvar1_1,
        CommandId::Qvar1_2,
        CommandId::Qvar1_3,
        CommandId::Qvar2_0,
        CommandId::Qvar2_1,
        CommandId::Qvar2_2,
        CommandId::Qvar2_3,
        CommandId::Qvar3_0,
        CommandId::Qvar3_1,
        CommandId::Qvar3_2,
        CommandId::Qvar3_3,
        CommandId::Qvar4_0,
        CommandId::Qvar4_1,
        CommandId::Qvar4_2,
        CommandId::Qvar4_3,
        CommandId::Qvar5_0,
        CommandId::Qvar5_1,
        CommandId::Qvar5_2,
        CommandId::Qvar5_3,
        CommandId::Qvar6_0,
        CommandId::Qvar6_1,
        CommandId::Qvar6_2,
        CommandId::Qvar6_3,
        CommandId::Qvar7_0,
        CommandId::Qvar7_1,
        CommandId::Qvar7_2,
        CommandId::Qvar7_3,
        CommandId::Qvar8_0,
        CommandId::Qvar8_1,
        CommandId::Qvar8_2,
        CommandId::Qvar8_3,
        CommandId::Qvar9_0,
        CommandId::Qvar9_1,
        CommandId::Qvar9_2,
        CommandId::Qvar9_3,
        CommandId::Qvar10_0,
        CommandId::Qvar10_1,
        CommandId::Qvar10_2,
        CommandId::Qvar10_3,
        CommandId::Qvar11_0,
        CommandId::Qvar11_1,
        CommandId::Qvar11_2,
        CommandId::Qvar11_3,
        CommandId::Qvar12_0,
        CommandId::Qvar12_1,
        CommandId::Qvar12_2,
        CommandId::Qvar12_3,
        CommandId::Qvar13_0,
        CommandId::Qvar13_1,
        CommandId::Qvar13_2,
        CommandId::Qvar13_3,
        CommandId::Qvar14_0,
        CommandId::Qvar14_1,
        CommandId::Qvar14_2,
        CommandId::Qvar14_3,
        CommandId::Qvar15_0,
        CommandId::Qvar15_1,
        CommandId::Qvar15_2,
        CommandId::Qvar15_3,
        CommandId::Qvar16_0,
        CommandId::Qvar16_1,
        CommandId::Qvar16_2,
        CommandId::Qvar16_3,
        CommandId::Qvar17_0,
        CommandId::Qvar17_1,
        CommandId::Qvar17_2,
        CommandId::Qvar17_3,
        CommandId::Qvar18_0,
        CommandId::Qvar18_1,
        CommandId::Qvar18_2,
        CommandId::Qvar18_3,
        CommandId::Qvar19_0,
        CommandId::Qvar19_1,
        CommandId::Qvar19_2,
        CommandId::Qvar19_3,
        CommandId::Qvar20_0,
        CommandId::Qvar20_1,
        CommandId::Qvar20_2,
        CommandId::Qvar20_3,
        CommandId::Qvar21_0,
        CommandId::Qvar21_1,
        CommandId::Qvar21_2,
        CommandId::Qvar21_3,
        CommandId::Qvar22_0,
        CommandId::Qvar22_1,
        CommandId::Qvar22_2,
        CommandId::Qvar22_3,
        CommandId::Qvar23_0,
        CommandId::Qvar23_1,
        CommandId::Qvar23_2,
        CommandId::Qvar23_3,
        CommandId::Qvar24_0,
        CommandId::Qvar24_1,
        CommandId::Qvar24_2,
        CommandId::Qvar24_3,
        CommandId::Qvar25_0,
        CommandId::Qvar25_1,
        CommandId::Qvar25_2,
        CommandId::Qvar25_3,
        CommandId::Qvar26_0,
        CommandId::Qvar26_1,
        CommandId::Qvar26_2,
        CommandId::Qvar26_3,
        CommandId::Qvar27_0,
        CommandId::Qvar27_1,
        CommandId::Qvar27_2,
        CommandId::Qvar27_3,
        CommandId::Qvar28_0,
        CommandId::Qvar28_1,
        CommandId::Qvar28_2,
        CommandId::Qvar28_3,
        CommandId::Qvar29_0,
        CommandId::Qvar29_1,
        CommandId::Qvar29_2,
        CommandId::Qvar29_3,
        CommandId::Qvar30_0,
        CommandId::Qvar30_1,
        CommandId::Qvar30_2,
        CommandId::Qvar30_3,
        CommandId::Qvar31_0,
        CommandId::Qvar31_1,
        CommandId::Qvar31_2,
        CommandId::Qvar31_3,
        CommandId::Qvar32_0,
        CommandId::Qvar32_1,
        CommandId::Qvar32_2,
        CommandId::Qvar32_3,
    ];

    #[test]
    fn all_lists_exactly_223_variants() {
        assert_eq!(ALL.len(), 223);
    }

    #[test]
    fn round_trip_every_variant_through_its_wire_name() {
        for &id in ALL {
            let name = command_id_name(id);
            assert_eq!(
                parse_command_id(name),
                Some(id),
                "round-trip failed for {id:?} (name {name:?})"
            );
        }
    }

    #[test]
    fn unknown_string_parses_to_none() {
        assert_eq!(parse_command_id("not-a-command"), None);
        assert_eq!(parse_command_id(""), None);
        assert_eq!(parse_command_id("Crossfader"), None);
    }

    /// Non-regression: hardcoded pairs taken directly from OpenDrop-VJ
    /// `src/lib/engine/commands.ts`, to catch a future accidental rename that the
    /// round-trip test alone wouldn't catch (round-trip only proves internal
    /// self-consistency, not agreement with the wire format other apps expect).
    #[test]
    fn non_regression_names_match_commands_ts() {
        let pairs: &[(CommandId, &str)] = &[
            (CommandId::Crossfader, "crossfader"),
            (CommandId::PresetPrevA, "preset-prev-a"),
            (CommandId::PlaylistToggleActive, "playlist-toggle-active"),
            (CommandId::LumakeyWhite2, "lumakey-white-2"),
            (CommandId::ColorkeyTolerance3, "colorkey-tolerance-3"),
            (CommandId::TimeWarp1, "time-warp-1"),
            (CommandId::OverlayQueuePrev, "overlay-queue-prev"),
            (CommandId::Qvar17_2, "qvar-17-2"),
        ];
        for (id, expected) in pairs {
            assert_eq!(command_id_name(*id), *expected);
        }
    }
}
